# config.yaml

# Data and feature lists
csv_file: "shopping_behavior_updated.csv"

numeric_features:
  - Age
  - Purchase Amount (USD)
  - Review Rating
  - Previous Purchases

categorical_features:
  - Gender
  - Item Purchased
  - Category
  - Location
  - Size
  - Color
  - Season
  - Subscription Status
  - Shipping Type
  - Discount Applied
  - Promo Code Used
  - Payment Method
  - Frequency of Purchases

# Target and Learning Setup
target: "Purchase Amount (USD)"

task_type: "regression"     # "classification" or "regression"
loss_function: "MSELoss"    # "MSELoss", "CrossEntropyLoss", etc.

# (You might also add optimizer, learning_rate, etc.)
optimizer:
  name: "Adam"
  learning_rate: 0.001
